config/routes.rb
Rails.application.routes.draw do
  #get 'comments/create'
  #get 'comments/destroy'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/approve', to: 'friendships#approve', as: 'friendship_request_approve'
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/reject', to: 'friendships#reject', as: 'friendship_request_reject'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/approve', to: 'transactions#approve', as: 'transaction_request_approve'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/reject', to: 'transactions#reject', as: 'transaction_request_reject'
  get '/:locale/conversations/:id/reply', to: 'conversations#reply', as: 'reply'

  scope "(:locale)", locale: /en|de|fr/ do
    root to: 'pages#home'
    resources :conversations do
      resources :transactions
    end
    # get '/locallects/filtered/', to: 'locallects#filter', as: 'locallects_filtered'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :locallects, only: [:index, :show, :new, :create, :edit]  do
      resources :friendships, only: [:index, :create, :destroy]
    end
    resources :forums do
      resources :comments, only: [:create, :destroy]
    end
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/locallect.rb
class Locallect < ApplicationRecord
  belongs_to :user
  has_many :friendships, dependent: :destroy
  has_many :transactions
end

app/controllers/locallects_controller.rb
class LocallectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :find_user, only: [:show]

  def index
    search = params[:search]
    gender_array = t("gender_array", locale: :en).zip(t("gender_array", locale: :de), t("gender_array", locale: :fr))
    language_array = t("language_array", locale: :en).zip(t("language_array", locale: :de), t("language_array", locale: :fr))
    hobby_array = t("hobby_array", locale: :en).zip(t("hobby_array", locale: :de), t("hobby_array", locale: :fr))
    picked_gender = gender_array.find { |sub_gender| sub_gender.include?(search[:gender]) }
    if search[:base_location].present?
      @locallects = policy_scope(User).search_by_base_location(search[:base_location].split(", ").first).order(created_at: :desc)
      @locallects = @locallects.where(age: (search[:start_age]..search[:end_age])) if search[:start_age] != '' && search[:start_age].present?
      @locallects = @locallects.search_by_gender(picked_gender.join(" ")) if !picked_gender.nil? && search[:gender].present?
      if search[:language_list] != [""]
        picked_languages = language_array.find_all { |sub_language| (sub_language & search[:language_list]).present? }
        @locallects = @locallects.tagged_with(picked_languages, any: true)
      end
      if search[:hobby_list] != [""]
        picked_hobbies = hobby_array.find_all { |sub_hobby| (sub_hobby & search[:hobby_list]).present? }
        @locallects = @locallects.tagged_with(picked_hobbies, any: true)
      end
    else
      @locallects = policy_scope(User).search_by_base_location(search[:query].split(", ").first).order(created_at: :desc)
    end

    @base_location = search[:query].present? ? search[:query] : search[:base_location]

    @hobby = search[:query].present? ? search[:query] : search[:hobby]
  end

  def show
    authorize @locallect
    @friendship = Friendship.new
  end

  def edit
    @locallect = User.find(current_user.id)
    authorize @locallect
  end

  private

  def find_user
    @locallect = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :gender, :base_location, :arrival_date, :seek_location, :mother_tongue)
  end

end

app/views/locallects/index.html.erb
<div class="p-5">
  <h2 class="ml-5 pl-3"><%= t(:people_in) %> <%= @base_location %> </h2>
  <div class="d-flex m-5">
    <!-- user cards  -->
    <div class="col-sm-9">
      <div class="row">
        <div class="filtertitle">
        </div>
        <% if current_user.nil? %>
          <% @locallects.each do |user| %>
            <div class="col-sm-4">
              <%= render 'shared/locallectslist', :user => user %>
            </div>
          <% end %>
        <% else %>
          <% @locallects.reject{|x| x == current_user}.each do |user| %>
            <div class="col-sm-4">
              <%# unless current_user.id == user.id %>
              <%= render 'shared/locallectslist', :user => user %>
              <%# end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- filter menu -->

    <div class="filter col-sm-3 sticky-top">
      <%= simple_form_for :search, url: locallects_path, method: "GET" do |f| %>


        <div class="form-inputs bg-light p-3">
          <div class="inline-block d-flex">
            <%= f.input :start_age, label: t(:start_age), input_html: {value: params[:search][:start_age]}, required: false %><%= f.input :end_age, label: t(:end_age), input_html: {value: params[:search][:start_age]}, required: false %>
          </div>
          <%= f.input :gender, label: t(:gender), collection: [t(:gender_all)].concat(t(:gender_array)), selected: params[:search][:gender], required: false %>
          <%= f.input :base_location, label: t(:base_loc), input_html: {value: @base_location}, required: false %>
          <%= f.input :language_list, label: t(:languages), collection: t(:language_array), input_html: {class: "select2 select-language",  multiple: "multiple"}, required: false %>
          <%= f.input :hobby_list, label: t(:hobbies), collection: t(:hobby_array), input_html: {class: "select2 select-hobby",  multiple: "multiple"}, required: false %>
          <%= f.button :submit, t(:search), class: "btn btn-outline-dark" %>
        </div>

      <% end %>
    </div>
  </div>

  <!-- pass translation to js file -->
  <script>
    var specify_language = <%= t(:specify_language).to_json.to_s.html_safe %>;
    var specify_hobby = <%= t(:specify_hobby).to_json.to_s.html_safe %>;
  </script>

app/views/locallects/show.html.erb
<div class="to-be-darkened">
  <div class="cover-by-popup-banner profile-banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @locallect.city_image %>);">
    <div class="home-banner-container">
    </div>
    <% if current_user.photo.file.nil? %>
      <div class= "cover-by-popup-image show-profile-image" style="background-image: url('<%= image_path 'default-avatar.png' %>');"></div>
    <% else %>
      <div class= "cover-by-popup-image show-profile-image" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(<%= @locallect.photo %>);"></div>
    <% end %>
  </div>
  <div class="mgt50"></div>
  <div class="page-bottom mb-3">
    <div class="cover-by-popup-box left-box text-center w-25">
      <h2 class="profile-name"><%= @locallect.first_name %> <%= @locallect.last_name %></h2>
      <br>
      <div class="attributes text-center">
        <% unless @locallect.base_location.nil? && @locallect.seek_location.nil? %>
          <p class=""><i class="fas fa-home"></i> &nbsp<% if @locallect.base_location.present? %> <%= @locallect.base_location.split(",")[0] %> <% else %> <%= @locallect.seek_location.split(",")[0] %> <% end %> </p>
        <% end %>
        <!-- since --> <%#= @locallect.arrival_date.strftime("%B %Y") %>
        <p class=""><i class="fas fa-user gender-icon"></i> &nbsp &nbsp</i><%= @locallect.gender %> - <%= @locallect.age %></p>
      </div>
      <!-- Check if you are friends and friendship was approved -->
      <% if current_user.friendships.any? {|friendship| @locallect.friendships.include?(friendship) && friendship.approved } %>
        <% current_user.mailbox.conversations.each do |conversation| %>
          <% conversation.participants.each do |participant| %>
            <% if participant == @locallect && participant != current_user %>
              <%= link_to t(:message_profile, locallect: @locallect.first_name), conversation_path(conversation), class: "btn btn-outline-dark" %>
            <% end %>
          <% end %>
        <% end %>
      <% elsif current_user.id == @locallect.id %>
        <%= link_to t(:edit_profile), edit_user_registration_path, class: "btn btn-outline-dark" %>
        <!-- Check if friend request was sent -->
      <% elsif current_user.friendships.any? {|friendship| @locallect.friendships.include?(friendship)} %>
        <p class="border"><%= t(:request_sent) %></p>
        <!-- else show button to send friend request -->
      <% elsif current_user.id != @locallect.id %>
        <%= link_to t(:gettoknow_profile, locallect: @locallect.first_name), "#", class: "btn btn-outline-dark request-button" %>
      <% end %>
    </div>
    <div class="rightside w-75">
      <div class="cover-by-popup-box right-box">
        <div class="aboutme">
          <h2 class="bio-title"><%= t(:about_me) %></h2>
          <br>
          <p class="bio-text"><%= @locallect.bio %></p>
        </div>
      </div>
      <div class="language-hobbies d-flex">
        <div class="cover-by-popup-box center-box mt-3 ">
          <i class="fas fa-language"></i>
          <% slash1 = @locallect.languages.count >= 1 ? " |" : nil %>
          <% string = ""  %>
          <% if slash1 %>
            <% @locallect.languages.each do |language| %>
              <% string << " #{language.name}#{slash1}" %>
            <% end  %>
          <% end  %>
          <p class="mt-1"><%= string.delete_suffix!(" |") %></p>
        </div>
        <div class="cover-by-popup-box center-box mt-3">
          <i class="fas fa-dumbbell"></i>
          <% slash2 = @locallect.hobbies.count >= 1 ? " |" : nil %>
          <% string2 = ""  %>
          <% if slash2 %>
            <% @locallect.hobbies.each do |hobby| %>
              <% string2 << " #{hobby.name}#{slash2}" %>
            <% end  %>
          <% end  %>
          <p class="mt-1"><%= string2.delete_suffix!(" |") %></p>
        </div>
      </div>
    </div>
  </div>
  <!-- Will only pop up if friend request will be send -->
  <div class="container w-50 border-radius p-5 request-field">
    <h3 class="my-3"><%= t(:become_friends, locallect: @locallect.first_name)%></h3>
    <%= simple_form_for(@friendship, url: locallect_friendships_path(@locallect), method: :post) do |f| %>
      <%= f.input :request_message, label: t(:about_you), class: "friendrequest-text" %>
      <%= f.button :submit, t(:send_request), class: "btn btn-outline-light" %>
    <% end %>
    <%= link_to locallect_path(@locallect) do %>
      <i class="fas fa-times cancel-cross"></i>
    <% end %>
  </div>
  <!-- pass both images as variables -->
  <script>
    const user = <%= @locallect.to_json.to_s.html_safe %>
  </script>