config/routes.rb
Rails.application.routes.draw do
  #get 'comments/create'
  #get 'comments/destroy'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/approve', to: 'friendships#approve', as: 'friendship_request_approve'
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/reject', to: 'friendships#reject', as: 'friendship_request_reject'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/approve', to: 'transactions#approve', as: 'transaction_request_approve'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/reject', to: 'transactions#reject', as: 'transaction_request_reject'
  get '/:locale/conversations/:id/reply', to: 'conversations#reply', as: 'reply'

  scope "(:locale)", locale: /en|de|fr/ do
    root to: 'pages#home'
    resources :conversations do
      resources :transactions
    end
    # get '/locallects/filtered/', to: 'locallects#filter', as: 'locallects_filtered'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :locallects, only: [:index, :show, :new, :create, :edit]  do
      resources :friendships, only: [:index, :create, :destroy]
    end
    resources :forums do
      resources :comments, only: [:create, :destroy]
    end
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :find_convo, only: [:show, :reply]

  def index
    @conversations = current_user.mailbox.conversations.order(updated_at: :desc)
    skip_policy_scope
  end

  def show
    authorize current_user
    @transaction = Transaction.new



    @conversation.participants.each do |participant|
      if current_user.id == participant.id
        @logged_in_chatter = participant
      else
        @other_chatter = participant
      end
    end

    @transactions = current_user.transactions
    @transactions.each do |transaction|
      if current_user.transactions.include?(transaction) && @other_chatter.transactions.include?(transaction)
        @transaction = transaction
      end
    end

    # need to find existing transaction between 2 user to update the record
    # @transaction = @transaction.geocode
    @markers = [
      {
        lat: @transaction.latitude,
        lng: @transaction.longitude
      }
    ]


    # marks conversation as read when user opens convo
    inbox = @conversation.receipts.where(mailbox_type: "inbox", receiver_id: @logged_in_chatter)
    inbox.mark_as_read
  end

  def reply
    current_user.reply_to_conversation(@conversation, params[:send_message])
    if @conversation.receipts[-2].mailbox_type == "inbox"
      @conversation.receipts[-2].mark_as_unread
      @conversation.receipts[-1].mark_as_read
    end

    if @conversation.receipts[-1].mailbox_type == "inbox"
      @conversation.receipts[-2].mark_as_read
      @conversation.receipts[-1].mark_as_unread
    end
    authorize current_user
    redirect_to conversation_path(@conversation)
  end

  private

  def find_convo
    current_user.mailbox.conversations.each do |conversation|
      if conversation.id == params[:id].to_i
        @conversation = conversation
      end
    end
  end

  def find_user
    @locallect = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :age, :gender, :base_location, :years_in_city, :explorer_location)
  end
end

app/views/conversations/index.html.erb
<div class="container my-4">
  <h1 class="py-3"><%= t(:conversations) %></h1>
  <% if @conversations == [] %>
    <h3><%= t(:no_conv_yet) %></h3>
  <% end %>
  <div class="friendships-grid">
    <% @conversations.each do |conversation| %>
      <div class="card-friend m-3">
        <% conversation.participants.each do |participant| %>
          <% if current_user.id != participant.id %>
            <% @other_chatter = participant %>
          <% end %>
        <% end %>
        <%= link_to conversation_path(conversation.id) do %>
          <%= cl_image_tag @other_chatter.photo, class: "card-friend-image ml-1" %>
        <% end %>
        <div class="convo-info">
          <div class="card-friend-infos ml-5">
            <%= link_to conversation_path(conversation.id) do %>
              <h4><%= @other_chatter.first_name %> <%= @other_chatter.last_name %></h4>
              <% if conversation.receipts.last.message.sender_id == current_user.id %>
                <h6><%= t(:conversations_you) %> <%= conversation.receipts.last.message.body %></h6>
              <% else %>
                <h6><%= @other_chatter.first_name %>: <%= conversation.receipts.last.message.body %></h6>
              <% end %>
            <% end %>
          </div>
          <div>
            <!-- counts number of unopened messages inside message_count variable -->
            <% message_count = 0 %>
            <% unread_messages = [] %>
            <% conversation.receipts.each do |message| %>
              <% unread_messages << message if message.is_read == false && message.mailbox_type == "inbox" && message.message.sender_id != current_user.id %>
            <% end %>
            <% unread_messages.each { message_count += 1 } %>
            <% if message_count > 0 %>
              <span class="badge badge-danger h-25"><%= message_count %></span>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/conversations/show.html.erb
<div class="to-be-darkened">
  <div class="messages-container">
    <div class="recipient-info cover-by-popup-box col-sm-4">
      <%= link_to(locallect_path(@other_chatter.id)) do %>
        <div class= "cover-by-popup-image-book chatter-photo ml-1" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(<%= @other_chatter.photo %>);"></div>
      <% end %>
      <%#= cl_image_tag @other_chatter.photo, class: "chatter-photo ml-1 cover-by-popup-image-book" %>
      <h2><%= link_to "#{@other_chatter.first_name} #{@other_chatter.last_name}", locallect_path(@other_chatter.id), class: "chatter-name-link" %></h2>
      <% if current_user.transactions.any? {|transaction| @other_chatter.transactions.include?(transaction) } %>
        <% @other_chatter.transactions.each do |transaction| %>
          <!-- Check if new transaction to be approved -->
          <% if current_user.transactions.include?(transaction) && transaction.approved == false && transaction.declined == false %>
            <h4><%= t(:proposed_meeting) %>:</h4>
            <p class="font-weight-bold mb-0"><%= t(:date) %>: <%= transaction.date.strftime("%A, %d %b %Y ") %></p>
            <p class="font-weight-bold"><%= t(:time) %>: <%= transaction.date.strftime("%I:%M %p") %></p>
            <p class="font-weight-bold">Location: <%= transaction.location %></p>
            <% if current_user.id == transaction.locallect_id %>
              <%= link_to 'Approve', transaction_request_approve_path(@conversation.id, transaction.id), class: "btn btn-outline-success mr-3" %>
              <%= link_to 'Reject', transaction_request_reject_path(@conversation.id, transaction.id), class: "btn btn-outline-danger" %>
            <% else %>
              <p><%= @other_chatter.first_name %> still has to approve</p>
            <% end %>
          <% end %>
          <!-- Check if new transaction that has been approved -->
          <% if current_user.transactions.include?(transaction) && transaction.approved == true %>
            <h3>Your next meeting:</h3>
            <p class="font-weight-bold mb-0">Date: <%= transaction.date.strftime("%A, %d %b %Y ") %></p>
            <p class="font-weight-bold">Time: <%= transaction.date.strftime("%I:%M %p") %></p>
            <p><%= t(:location) %>: <%= transaction.location %></p>
            <div id="map" style="width: 100%; height: 44%;" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
          <% end %>
          <!-- Check if new transaction that has been declined -->
          <% if current_user.transactions.include?(transaction) && transaction.declined == true && current_user.id == transaction.explorer_id%>
            <h3><%= @other_chatter.first_name %> <%= t(:unfortunately_no_time) %> <%= transaction.date.strftime("%A, %d %b %Y %l:%M %p") %></h3>
          <% end %>
        <% end %>
        <p class=""><%= link_to t(:change_meeting), "#", class: "request-button btn btn-outline-dark m-2"%></p>
      <% else %>
        <%= link_to t(:meet) "#{@other_chatter.first_name}", "#", class: "request-button btn btn-outline-dark m-2" %>
      <% end %>
    </div>
    <div class="message-list-container col-sm-8 px-0">
      <div class="message-list cover-by-popup-box">
        <% unordered = @conversation.receipts_for current_user%>
        <% receipts = unordered.order(created_at: :desc) %>

        <div class="conversations-container">
          <% receipts.reverse.each_with_index do |receipt,index| %>
            <% if receipt.message.sender_id == current_user.id %>
              <div class="single-message-container r">
                <div class="card-conversation r text-dark cover-by-popup-box">
                  <div class="card-product-infos">
                    <p class="message-co"> <%= message = receipt.message.body %></p>
                  </div>
                </div>
                <div class="p-1"></div>
                  <%#= cl_image_tag @logged_in_chatter.photo, class: "avatar ml-1 cover-by-popup-image-book" %>
                <div class= "avatar chat-photo-user cover-by-popup-image-book-me ml-1" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(<%= current_user.photo %>);"></div>
              </div>
              <% date = receipt.message.created_at.to_s.split(" ") %>
              <% time = date[1].split(":") %>
              <div class="text-right mr-5 pr-4">
                <p class="small mb-1"><%= time[0]%>:<%= time[1] %>, <%= date[0] %></p>
              </div>
            <% else %>
              <div class="single-message-container l">
                <%#= cl_image_tag @other_chatter.photo, class: "avatar ml-1 cover-by-popup-image-book" %>
                <div class= "avatar chat-photo-user cover-by-popup-image-book ml-1" style="background-image: linear-gradient(rgba(0,0,0,0),rgba(0,0,0,0)), url(<%= @other_chatter.photo %>);"></div>
                <div class="p-1"></div>
                <div class="card-conversation text-dark cover-by-popup-box">
                  <div class="card-product-infos">
                    <p> <%= message = receipt.message.body %></p>
                  </div>
                </div>
              </div>
              <% date = receipt.message.created_at.to_s.split(" ") %>
              <% time = date[1].split(":") %>
              <div class="ml-5 pl-4">
                <p class="small mb-1"><%= time[0]%>:<%= time[1] %>, <%= date[0] %></p>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="send-message-field">
        <%= form_tag(reply_path(id: @conversation.id), method: :get) do %>
          <div class="input-container">
            <div class="message-box">
              <%= text_field_tag :send_message, nil, placeholder: "Type a message...",class: "message-input cover-by-popup-box border-0 pl-3" %>
            </div>
            <%= submit_tag "Send",class: "bgd-white btn btn-secondary cover-by-popup-button send-btn"%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<!-- Will only pop up if meeting takes place -->
<div class="container w-50 border-radius p-5 request-field">
  <h3 class="my-3"><%= t(:arrange_meeting) %></h3>
  <%= simple_form_for(@transaction, url: conversation_transactions_path(@conversation), method: :post) do |f| %>
    <%= f.error_notification %>
    <div class="form-inputs">
      <%= f.input :date, as: :string, input_html: {class: "datepicker2 bg-white"}, label: t(:date) %>
      <%= f.input :location, as: :string, label: t(:location) %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, t(:send), class: "btn btn-outline-light" %>
    </div>
  <% end %>
  <%= link_to conversation_path(@conversation) do %>
    <i class="fas fa-times cancel-cross"></i>
  <% end %>
</div>
<script>
  const chatter = <%= @other_chatter.to_json.to_s.html_safe %>;
  const current_user = <%= current_user.to_json.to_s.html_safe %>;
</script>