config/routes.rb
Rails.application.routes.draw do
  #get 'comments/create'
  #get 'comments/destroy'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/approve', to: 'friendships#approve', as: 'friendship_request_approve'
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/reject', to: 'friendships#reject', as: 'friendship_request_reject'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/approve', to: 'transactions#approve', as: 'transaction_request_approve'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/reject', to: 'transactions#reject', as: 'transaction_request_reject'
  get '/:locale/conversations/:id/reply', to: 'conversations#reply', as: 'reply'

  scope "(:locale)", locale: /en|de|fr/ do
    root to: 'pages#home'
    resources :conversations do
      resources :transactions
    end
    # get '/locallects/filtered/', to: 'locallects#filter', as: 'locallects_filtered'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :locallects, only: [:index, :show, :new, :create, :edit]  do
      resources :friendships, only: [:index, :create, :destroy]
    end
    resources :forums do
      resources :comments, only: [:create, :destroy]
    end
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_locallectslist.html.erb
<%= link_to locallect_path(user.id) do %>
  <div id="curve" class="card mb-4">
    <div class="index-circle-photo-container  h-75">
    <%= user.photo.url.nil? ? (image_tag "user-solid.svg") : (cl_image_tag user.photo, class: "index-circle-photo", width: 250, height: 220, crop: :fill) %>
    </div>
    <div class="footer-up p-0">
      <svg id="curve">
        <path id="p" d="M0,200 Q80,100 400,200 V150 H0 V50" transform="translate(0 300)" />
        <!-- slide up-->
        <animate xlink:href="#p" attributeName="d" to="M0,50 Q80,100 400,50 V150 H0 V50" fill="freeze" begin="dummyRect.mouseover" end="dummyRect.mouseout" dur="0.1s" id="bounce1" />
        <!-- slide up and curve in -->
        <animate xlink:href="#p" attributeName="d" to="M0,50 Q80,0 400,50 V150 H0 V50" fill="freeze" begin="bounce1.end" end="dummyRect.mouseout" dur="0.15s" id="bounce2" />
        <!-- slide down and curve in -->
        <animate xlink:href="#p" attributeName="d" to="M0,50 Q80,80 400,50 V150 H0 V50" fill="freeze" begin="bounce2.end" end="dummyRect.mouseout" dur="0.15s" id="bounce3" />
        <!-- slide down and curve out -->
        <animate xlink:href="#p" attributeName="d" to="M0,50 Q80,45 400,50 V150 H0 V50" fill="freeze" begin="bounce3.end" end="dummyRect.mouseout" dur="0.1s" id="bounce4" />
        <!-- curve in -->
        <animate xlink:href="#p" attributeName="d" to="M0,50 Q80,50 400,50 V150 H0 V50" fill="freeze" begin="bounce4.end" end="dummyRect.mouseout" dur="0.05s" id="bounce5" />
        <animate xlink:href="#p" attributeName="d" to="M0,200 Q80,100 400,200 V150 H0 V50" fill="freeze" begin="dummyRect.mouseout" dur="0.15s" id="bounceOut" />
      </svg>
      <div class="info bg-light">
        <div class="name"><%= user.first_name %> <%= user.last_name %></div>
        <p class="text-center"><%= user.base_location.split(",")[0] %> - <%= user.gender %> - <%= user.age %></p>
        <div class="job d-flex justify-content-between">
        </div>
      </div>
    </div>
    <div class="card-blur"></div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon d-flex">
  <div class="container navbar-container">
    <div>
      <!-- brand logo -->
      <%= link_to root_path, class: "navbar-brand" do %>
        <%= image_tag "https://res.cloudinary.com/dd8gqkm50/image/upload/v1575428610/locallectuallogo_ocbhoy.png" %>
      <% end %>
      <!-- add locallectual -->
    </div>
    <!-- navbar paths -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          <% if user_signed_in? %>
            <%= link_to t(:forum), forums_path, class: "btn btn-warning navbar-button-text mx-3" %>
          <% end %>
          <!-- counts number of unresponded friend requests inside connection_count variable -->
          <% connection_count = 0 %>
          <% requests = [] %>
          <% current_user.locallect.friendships.each do |friendship| %>
            <% requests << friendship if friendship.approved == false && friendship.declined == false %>
          <% end %>
          <% requests.each { connection_count += 1 } %>
          <!-- counts number of unopened messages inside message_count variable -->
          <% message_count = 0 %>
          <% unread_messages = [] %>
          <% current_user.mailbox.receipts.each do |message| %>
            <% unread_messages << message if message.is_read == false && message.mailbox_type == "inbox" %>
          <% end %>
          <% unread_messages.each { message_count += 1 } %>
          <%= link_to t(:messages), conversations_path, class: "navbar-text mr-1 ml-3" %>
          <% if message_count.nil? == false %>
            <% if message_count > 0 %>
              <span class="badge badge-danger h-25"><%= message_count %></span>
            <% end %>
          <% end %>
          <%= link_to t(:connections), locallect_friendships_path(current_user.id), class: "navbar-text mr-1 ml-3" %>
          <% if connection_count > 0 %>
            <span class="badge badge-danger h-25"><%= connection_count %></span>
          <% end %>
          <li class="nav-item dropdown ml-4">
            <%= current_user.photo.file.nil? ? (image_tag "default-avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) : (cl_image_tag current_user.photo, width: 60, height: 60, crop: :fill, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <%= link_to t(:view_profile), locallect_path(current_user), class: "dropdown-item" %>
              <%= link_to t(:edit_profile), edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to t(:logout), destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <!-- if not signed in -->
          <%= link_to t(:forum), forums_path, class: "btn btn-warning navbar-button-text mx-3" %>
          <li class="nav-item">
            <%= link_to t(:login), new_user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to t(:signup), new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="dropdown">
    <i class="fas fa-globe-americas mr-3 language-dropdown" id="languageDropDown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></i>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="languageDropDown">
      <%= link_to "Deutsch", root_path("de"), class: "dropdown-item" %>
      <%= link_to "English", root_path("en"), class: "dropdown-item" %>
      <%= link_to "French", root_path("fr"), class: "dropdown-item" %>
      <%= link_to "العربية", root_path("en"), class: "dropdown-item" %>
    </div>
  </div>
</div>