config/routes.rb
Rails.application.routes.draw do
  #get 'comments/create'
  #get 'comments/destroy'
  devise_for :users, controllers: {registrations: 'users/registrations'}
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/approve', to: 'friendships#approve', as: 'friendship_request_approve'
  get '/:locale/locallects/:locallect_id/friendships/:friendship_id/reject', to: 'friendships#reject', as: 'friendship_request_reject'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/approve', to: 'transactions#approve', as: 'transaction_request_approve'
  get '/:locale/conversations/:conversation_id/transactions/:transaction_id/reject', to: 'transactions#reject', as: 'transaction_request_reject'
  get '/:locale/conversations/:id/reply', to: 'conversations#reply', as: 'reply'

  scope "(:locale)", locale: /en|de|fr/ do
    root to: 'pages#home'
    resources :conversations do
      resources :transactions
    end
    # get '/locallects/filtered/', to: 'locallects#filter', as: 'locallects_filtered'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    resources :locallects, only: [:index, :show, :new, :create, :edit]  do
      resources :friendships, only: [:index, :create, :destroy]
    end
    resources :forums do
      resources :comments, only: [:create, :destroy]
    end
  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :locallect
  belongs_to :explorer
  # make sure that you can not have a friendship that already exists
  validates :locallect_id, uniqueness: {scope: :explorer_id}

  def users
    User.joins("LEFT JOIN explorers e ON e.user_id = users.id LEFT JOIN locallects l ON l.user_id = users.id LEFT JOIN friendships fe ON fe.explorer_id = e.id LEFT JOIN friendships fl ON fl.locallect_id = l.id ").where("fe.id = ? OR fl.id = ?", self.id, self.id).uniq
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def index
    @friendship_requests = current_user.friendships.where("friendships.approved = ? and friendships.locallect_id = ? and friendships.declined = ?", false, current_user.id, false).order(created_at: :desc)
    @friendship_requests_sent = policy_scope(current_user.friendships).where("friendships.approved = ? and friendships.explorer_id = ? and friendships.declined = ?", false, current_user.id, false).order(created_at: :desc)
    @friendships_approved = policy_scope(current_user.friendships).where("friendships.approved = ?", true).order(created_at: :desc)
  end

  def create
    @friendship = Friendship.new
    if policy(@friendship).create?
      @locallect = User.find(params[:locallect_id])
      @friendship = Friendship.create(request_message: params[:friendship][:request_message])
      @friendship.approved = false
      @friendship.declined = false
      @friendship.locallect_id = @locallect.id
      @friendship.explorer_id = current_user.id
      @friendship.save!
      flash[:alert] = "Friendship request has been sent!"

      # send email
      mail = UserMailer.with(user: @locallect.id, sender: current_user.id).friendrequest
      mail.deliver_later

      redirect_to locallect_path(@locallect)
      authorize @friendship
    else
      skip_authorization
      redirect_to edit_user_registration_path
      flash[:alert] = "You need to add a picture and your birthday to do this!"
    end
  end

  def approve
    @friendship = Friendship.find(params[:friendship_id])
    @friendship.approved = true
    @friendship.save
    flash[:alert] = "Friendship request has been approved!"

    # send email
    user = User.find(Locallect.find(@friendship.locallect_id).user_id).id == current_user.id ? User.find(Explorer.find(@friendship.explorer_id).user_id) : User.find(Locallect.find(@friendship.locallect_id).user_id)
    mail = UserMailer.with(user: user.id, sender: current_user.id).friendrequest_approval
    mail.deliver_later


    authorize @friendship
    current_user.send_message(User.find(@friendship.explorer_id), "Hey, I've accepted your friend request. Let's chat!", "Conversation between #{@friendship.users.first.first_name} and #{@friendship.users.last.first_name}")
    redirect_to locallect_friendships_path(current_user)
  end

  def reject
    @friendship = Friendship.find(params[:friendship_id])
    @friendship.declined = true
    @friendship.save
    flash[:alert] = "Friendship request has been rejected!"
    authorize @friendship
    redirect_to locallect_friendships_path(current_user)
  end

  def destroy
    @friendship = Friendship.find(params[:id])
    @friendship.destroy
    current_user.mailbox.conversations.each do |conversation|
      conversation.participants.each do |participant|
        if participant == User.find(Locallect.find(params[:locallect_id]).user_id)
          conversation.destroy
        end
      end
    end
    redirect_to locallect_friendships_path(current_user)
    authorize @friendship
  end

end

app/views/friendships/index.html.erb
<div class="container">
  <!-- counts number of unresponded friend requests inside connection_count variable -->
  <% connection_count = 0 %>
  <% requests = [] %>
  <% current_user.locallect.friendships.each do |friendship| %>
    <% requests << friendship if friendship.approved == false && friendship.declined == false %>
  <% end %>
  <% requests.each { connection_count += 1 } %>
  <nav>
    <div class="nav nav-tabs mt-3" id="nav-tab" role="tablist">
      <a class="nav-item nav-link tab-item active" id="nav-home-tab" data-toggle="tab" href="#nav-home" role="tab" aria-controls="nav-home" aria-selected="true">Connections</a>
      <a class="nav-item nav-link tab-item" id="nav-profile-tab" data-toggle="tab" href="#nav-profile" role="tab" aria-controls="nav-profile" aria-selected="false"><%= t(:friend_requests) %>
        <% if connection_count.nil? == false %>
          <% if connection_count > 0 %>
            &nbsp<span class="badge badge-danger"><%= connection_count %></span>
          <% end %>
        <% end %></a>
      <a class="nav-item nav-link tab-item" id="nav-contact-tab" data-toggle="tab" href="#nav-contact" role="tab" aria-controls="nav-contact" aria-selected="false"><%= t(:friend_requests_sent) %></a>
    </div>
  </nav>
  <div class="tab-content" id="nav-tabContent">
    <!-- connections -->
    <div class="tab-pane fade mt-4 show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
      <div class="friendships-grid">
        <!-- iterate over all friendships -->
        <% @friendships_approved.each do |friendship| %>
          <!-- iterate over both users connected to this friendship -->
          <% friendship.users.each do |user| %>
            <!-- dont show yourself -->
            <% if user.id != current_user.id %>
              <div class="card-friend">
                <!-- user-card/clickable to go to their profile -->
                <%= link_to locallect_path(user.id) do %>
                  <%= cl_image_tag user.photo, width: 90, height: 90, crop: :fill, class: "card-friend-image ml-1" %>
                  <div class="d-flex justify-content-between card-friend-content align-items-center">
                    <div class="card-friend-infos ml-3">
                      <h2><%= user.first_name %> <%= user.last_name %></h2>
                      <p><%= t(:connected_since) %> <strong><%= friendship.created_at.strftime("%A, %b %d") %></strong></p>
                    </div>
                    <div class="d-flex align-items-center">
                      <!-- message button link logic -->
                      <% current_user.mailbox.conversations.each do |conversation| %>
                        <% conversation.participants.each do |participant| %>
                          <% if participant == user && participant != current_user %>
                            <%= link_to t(:message_profile, locallect: user.first_name), conversation_path(conversation), class: "btn btn-outline-dark" %>
                            <% if policy(friendship).destroy? %>
                              <%= link_to locallect_friendship_path(locallect_id: friendship.locallect_id, id: friendship.id), method: :delete, data: {confirm: t(:confirmation_question_destroy)},class: "ml-3" do %>
                                <div class ="delete-user">
                                  <i class="fas fa-user-minus"></i>
                                </div>
                              <% end %>
                            <% end %>
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- friend requests -->
    <div class="tab-pane mt-4 fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab">
      <div class="friendships-grid">
        <!-- iterate over all friendships -->
        <% @friendship_requests.each do |friendship| %>
          <!-- iterate over both users connected to this friendship -->
          <% friendship.users.each do |user| %>
            <!-- dont show yourself -->
            <% unless user.id == current_user.id %>
              <div class="card-friend">
                <!-- user-card/clickable to go to their profile -->
                <%= link_to locallect_path(user.id) do %>
                  <%= user.photo.url.nil? ? (image_tag "user-solid.svg", class: "card-friend-image ml-1") : (cl_image_tag user.photo, width: 90, height: 90, crop: :fill, class: "card-friend-image ml-1") %>
                  <div class="d-flex justify-content-between card-friend-content align-items-center">
                    <div class="card-friend-infos ml-3">
                      <h2><%= user.first_name %> <%= user.last_name %></h2>
                    </div>
                    <div class="response-btns">
                      <%= link_to t(:approve), friendship_request_approve_path(current_user.id, friendship.id), class: "btn btn-outline-success mr-3" %>
                      <%= link_to t(:reject), friendship_request_reject_path(current_user.id, friendship.id), class: "btn btn-outline-danger" %>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
    <!-- friend requests sent -->
    <div class="tab-pane mt-4 fade" id="nav-contact" role="tabpanel" aria-labelledby="nav-contact-tab">
      <div class="friendships-grid">
        <!-- iterate over all friendships -->
        <% @friendship_requests_sent.each do |friendship| %>
          <!-- iterate over both users connected to this friendship -->
          <% friendship.users.each do |user| %>
            <!-- dont show yourself -->
            <% unless user.id == current_user.id %>
              <div class="card-friend">
                <!-- user-card/clickable to go to their profile -->
                <%= link_to locallect_path(user.id), class: "flex" do %>
                  <%= user.photo.url.nil? ? (image_tag "user-solid.svg", class: "card-friend-image ml-1") : (cl_image_tag user.photo, width: 90, height: 90, crop: :fill, class: "card-friend-image ml-1") %>
                  <div class="d-flex justify-content-between card-friend-content align-items-center">
                    <div class="card-friend-infos ml-3">
                      <h2><%= user.first_name %> <%= user.last_name %></h2>
                      <p><%= t(:request_sent) %> (<strong><%= friendship.created_at.strftime("%A, %d %b %Y %l:%M %p") %></strong>)</p>
                    </div>
                  </div>
                <% end %>
              </div>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>